### ISSUE TITLE
[BUG] Dimmer does not work anymore

### ISSUE THREAD

**Issue by Miicki** [johannrichard/homebridge-dingz#256]
Hello Johann,

I have the following problem since the latest update:

I have 2 buttons configured as switches and one as a dimmer. The switches work fine, but the dimmer does not work in Homekit and in Homebridge.
With the dimmer (in Homekit/Homebridge) I can only turn the light on and off, but not dim it.  In the Dingz app the dimming works and this value is also displayed in Homekit and the Homebrige.

Dingzplugin is version 3.1.4
Homebridge is version 1.2.5
node.js is version 14.15.4
nmp is version 6.14.10

I uninstalled the dingz plugin and then reinstalled it.

Thanks for your help,
Michael

**Comment by johannrichard** [comment]
Hi Michael

Sorry to hear your dimmers don't work. May I kindly ask you to provide the output from the following URLs -- that would help termendously with debugging:
```
http://<dingzIP>/api/v1/device
http://<dingzIP>/api/v1/dimmer
http://<dingzIP>/api/v1/dimmer_config
```

Also what was the version of the plugin you used while it was still working?

**Comment by Miicki** [comment]
Hi Johann,

device:
{"246F28A7DE48":{"type":"dingz","battery":false,"reachable":true,"meshroot":true,"fw_version":"1.2.7","hw_version":"1.1.2","fw_version_puck":"1.1.21","bl_version_puck":"1.0.0","hw_version_puck":"1.1.2","hw_id_puck":65535,"puck_sn":"B20050300004","puck_production_date":{"year":20,"month":5,"day":3},"puck_hw_model":"DZ1B-4CH","front_hw_model":"dz1f-4b","front_production_date":"20/4/28","front_sn":"F20042800196","dip_config":3,"has_pir":false,"hash":"e6e52dab"}}

dimmer:

{"0":{"on":false,"value":0,"ramp":0,"disabled":false,"index":{"relative":0,"absolute":0}},"1":{"on":false,"value":0,"ramp":0,"disabled":false,"index":{"relative":1,"absolute":1}},"2":{"on":false,"value":0,"ramp":0,"disabled":false,"index":{"relative":2,"absolute":2}},"3":{"on":false,"value":0,"ramp":0,"disabled":false,"index":{"relative":3,"absolute":3}}}

dimmer_config:

{"dimmers":[{"output":"halogen","name":"Dimmer","feedback":null,"feedback_intensity":100},{"output":"non_dimmable","name":"Eingang","feedback":null,"feedback_intensity":100},{"output":"non_dimmable","name":"Essbereich","feedback":null,"feedback_intensity":100},{"output":"led","name":"Wandleuchten","feedback":null,"feedback_intensity":100}]}

I don't remember the version number where it worked. In any case, it worked on the version before the version that made the plugin run under Hoobs (the version before v1.6.1).
Thanks for the quick help!

**Comment by johannrichard** [comment]
Thanks for the info. I will setup my test-dingz with such a configuration. At first sight I don't see anything special and it looks like a configuration that's quite normal. 

Do you use a Home Hub (iPad or Apple TV or Home Pod Speaker) with your HomeKit setup?

Before you try the steps out further down, did you try the following:

- changing the dimmer to non-dimmable (or not-connected), 
- restart Homebridge, 
- change the lamp back to dimmable, and 
- restart Homebridge again? 

this should reliably trigger a detection run of the configuration. The newest version of the plugin follows changed configurations, including switching from dimmable to non dimmable or non-connected or shades and vice-versa.

If that doesn't work, just to be sure we didn't miss anything and while waiting for the findings on my side:

- do you see any error messages from the plugin if you try to dim the light (or when doing nothing)?
- besides re-installing the plug-in, did you try removing the accessory from the accessory cache in Homebridge (can be found in the options and you can remove one single device - just don't forget to restart Homebridge) and what happens then? and
- if you enable debug logs, do you see what the plugin detects in terms of configuration (it should tell and change the configuration if it detects a change, including changing from dimmer to non-dimmer)?

**Comment by Miicki** [comment]
First of all: It works again (for the moment)

To answer your questions:

I'm using an Apple TV 4K as a Homekit Hub.

I changed the lights from dimmable to not dimmable and back as you wrote. Without success. I saw in the log that Homebridge/Homekit detected the changes.

I did not get any error messages.

I wanted to clear the Accessory Cache, but I didn't have the option. (Now I know that Homebridge has to run as a service for this).

I did not see any errors in the logs.

I also tried the following:

- I tried a rollback to different versions of your plugin - without success. At last the homebridge didn't start anymore (maybe an error in the config.json)

- I rebuilt the homebrige from scratch and installed only your plugin: It worked without problems.

- I installed the homebridge-hue v0.12.20 plugin and the dimming stopped working again.

- I uninstalled the homebridge-hue plugin again but the error was still there.

- I installed the homebridge as a service (hb-service) (to get the option to delete the accessory chache). (hue plugin is installed again).

- After clearing the cache it works now.

I don't know, but it seems to have something to do with the homebridge-hue plugin.

**Comment by johannrichard** [comment]
Glad to hear it works for the moment. I suggest we keep the ticket open a while so you can test if it works reliably.

**Comment by shan-vosseller** [comment]
I have the same issue and same configuration. The only thing that fixes it is clearing the cache. The problem with clearing the cache (besides being a pain) is that it also messes up my automation in homekit. After some extended period of time and a server reboot (full reboot of OS, docker, etc) it then seems to go bad. Bottom line - appears to be an issue with something bad in the cache.

**Comment by shan-vosseller** [comment]
I will keep it in this bad state in case there is something that may help with debugging.

**Comment by johannrichard** [comment]
@shan-vosseller thanks for reporting this. This is really weird – I also use `homebridge-hue` on the same HomeBridge server as the dingz plugin and don't have any issues with dimmers. 

For the debugging, just one clarification: Did you clear the *complete* accessory cache or just the dingz (because there's both options)?

In Homebridge (with insecure mode) it is also possible to control devices directly (On the "Accessories" Tab). If you try to dim from there, what happens? 

If it works from Homebridge "Accessories", what iOS versions are you running your iPhone / Apple TV devices on?

**Comment by johannrichard** [comment]
> In Homebridge (with insecure mode) it is also possible to control devices directly (On the "Accessories" Tab). If you try to dim from there, what happens?
> 
> If it works from Homebridge "Accessories", what iOS versions are you running your iPhone / Apple TV devices on?

Just forget what I wrote. I did a minor upgrade to the latest `homebridge-oznu` image (mine was still at node `14.15.1`or so, not ` 14.15.4`, so a few weeks back) and now I see the same behavior. 🙈 no idea what the reason might be yet – but at least I can reporduce it. 🙈 I shall dig into the code then. :octocat: 🐙 :code:

**Comment by shan-vosseller** [comment]
I only cleared Dingz accessory from the cache. I'm not using homebridge-hue btw so I think that's not a factor in this problem. I have insecure mode on but no accessories show up in that homebridge tab (but do show up on my apple devices all running the latest OS). I have an AppleTV 4k as homekit hub. I've never actually used the homebridge accessories tab....

I'm running the oznu image btw and I now realize it's probably old.

Node.js Version v12.18.3
npm Verison v6.14.6

**Comment by Miicki** [comment]
"Good" that you can reproduce the behavior in the meantime.

The same here. 

A few hours after clearing the cache it works and suddenly dimming doesn't work again.
Clearing the cache of Dingz was enough by the way.

Dimming via the Homebridge UI behaves the same as in HomeKit. That means that if it doesn't work in HomeKit, it doesn't work there either. If it works in Homebridge, it works in HomeKit.

I don't know if it matters or not:
I use a MyStrom Plug in addition to a Hue Bridge with a couple of Zigbee switches. This is also controlled via the Homebridge in HomeKit.

**Comment by johannrichard** [comment]
Thanks for your comments and further details. I have an idea what's happening when the brightness is set and where to look for a fix. What I have to investigate is why this error got caught only now. Either I completely missed this when rebuilding for v3 :see_no_evil: or it is indeed related to changes in `homebridge`. 

By experience, it's usually on my side. 😊

**Comment by shan-vosseller** [comment]
Updated to latest oznu image and redid container. I'm now running node 14.15.4 with latest homebridge and I can now see the accessories but the accessories for the dimmer in homebridge (and homekit ios) still has the same problem FWIW.

**Comment by johannrichard** [comment]
I've pushed an alpha version (`3.1.5-alpha.2`) that implements changes to better reflect the Dimmer configuration on restarts without config changes. This should more reliably enforce that we really listen to the "setBrightness" event. It's difficult to tell if this was a bug that was there for some time, if it only occurred due to other changes upstream or if I'd just plain missed it (probably the latter 🙈).

I've installed it on my servers and have done some back and forth between this version and the old version. So far, I could reliably reproduce the error w/ the old version(s) directly after restarting Homebridge and had the correct behavior when upgrading to the alpha. I did no cache clearing or so in between. So I'm quite confident this could fix it for you, too. Let me know your findings, please.

**Comment by johannrichard** [comment]
> I've pushed an alpha version (3.1.5-alpha.2) that implements changes to better reflect the Dimmer configuration on restarts without config changes. 

Just a note: the change is a bit of a hack, as I remove and then add the "Brightness" characteristic again. I can not exclude that complicated automation (e.g. setting specific brightness levels in scenes and the like) will break because of that whenever the Homebridge server is restarted or another config change happens. I'll have to observe this a bit and see what it does to Automation.

It's kind of the flip-side of the dingz being so flexible and configurable: 

- the plugin can, as it does, either try to track the changing configuration in a reliable way (but change some of what HomeKit sees in the process); or
- it can avoid tracking any changes at all, forcing the user to rebuild the accessory cache whenever one of these configurations like dimming/non-dimming light changes. 

From a UX perspective, I am still convinced that the implemented option is better than the second one.

**Comment by shan-vosseller** [comment]
Alpha 2 seems to fix it for me. I will give it some time with my scenes and will report any issues.
